### ISSUE TITLE
Source map error:  404

### ISSUE THREAD

**Issue by poetaster** [dev-rke/CalDav-Web-Client#3]
Source map error: Error: request failed with status 404
Resource URL: https://cal.netzpolitik.org/jquery.min.js
Source Map URL: jquery.min.map

something is not being found?

**Comment by dev-rke** [comment]
And you are reporting here because of....? ;-)

**Comment by poetaster** [comment]
I was hoping to solve the issue, but as I don't have any experience with coffee script and co. thought I'd see if a developer could assist.

**Comment by poetaster** [comment]
Just to clarify, I need a 'read only' view of multiple calendars and running caldavzap is really overkill. You project seemed like one of the few options out there ;)

**Comment by dev-rke** [comment]
Hi @poetaster ,

thanks for clarification. 
I just saw caldavzap on the provided url and did not understand why you asked me about this. ;-)
You are not developer, right? BOFH seems to be more like system administrator. ;-)
.map files are just source maps, these files are not required to work, they are just helpful for debugging purposes.

In my opinion your caldav server does not work or is not compatible to my project.
If you need further assistence, i need more details. If you prefer, i can contact you via email, so you don't have to share too much details of your system setup in this issue.
